#!/usr/bin/env python3
"""End-to-end smoke test of the Reviewer's check scripts — DEV TOOL, not runtime.

`test_orchestrate.py` covers the decision table and `check_examples.py` covers
the artifact shapes. Neither touches the three scripts that actually drive
maven — and those are the ones that break, because they depend on the JDK, on
the JaCoCo agent being attached exactly once, and on PIT finding a JUnit 5
plugin. Their failure mode is exit code 2, "the check could not run", which the
Reviewer must read as BLOCKED: the pipeline stops and a human is called.

So this tool builds the smallest valid plan and generation report for a real
target in the repository, runs the three scripts against it, and asserts that
none of them exits 2 and that every check report it wrote parses.

It deliberately does NOT assert that the gates pass. Exit 1 means the scripts
ran and found a quality defect, which is a legitimate verdict about the tests,
not a broken pipeline. Exit 2 is the failure this tool exists to catch.

Usage:
    python .github/agents/common/tools/smoke_pipeline.py [--target SimpleCalculatorService]
                                                         [--repo .] [--skip-mutation]
                                                         [--keep]

Exit codes:
    0 — every script ran and its report parses
    1 — a script could not run, or wrote a report that does not parse
    2 — the smoke test could not be set up (no target, no test class, no git)
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve()
AGENTS = HERE.parents[2]
sys.path.insert(0, str(AGENTS / "common" / "scripts"))

from md_payload import load_payload  # noqa: E402

REVIEWER = AGENTS / "test-reviewer" / "scripts"
SKIP_DIRS = {"target", "build", "out", ".git", ".test-agent"}


def find_one(repo: Path, *names: str) -> Path | None:
    for name in names:
        for path in repo.rglob(f"{name}.java"):
            if not SKIP_DIRS.intersection(path.parts):
                return path
    return None


def head_sha(repo: Path) -> str | None:
    result = subprocess.run(["git", "rev-parse", "HEAD"], cwd=repo,
                            capture_output=True, text=True)
    return result.stdout.strip() or None


def container(title: str, payload: dict) -> str:
    return (f"# {title}\n\nGenerated by smoke_pipeline.py — safe to delete.\n\n"
            f"```json\n{json.dumps(payload, indent=2)}\n```\n")


def setup(repo: Path, target: str) -> tuple[Path, str]:
    """Write the smallest plan + report the check scripts accept."""
    source = find_one(repo, target)
    if source is None:
        raise SystemExit(f"CANNOT_RUN: no {target}.java under {repo}")
    test_source = find_one(repo, f"{target}Test", f"{target}Tests")
    if test_source is None:
        raise SystemExit(f"CANNOT_RUN: no {target}Test.java or {target}Tests.java — "
                         f"the smoke test needs an existing test class to run")
    sha = head_sha(repo)
    if sha is None:
        raise SystemExit("CANNOT_RUN: not a git checkout, so the plan cannot record target_sha")

    test_method = None
    for line in test_source.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if stripped.startswith("void ") and stripped.endswith("{"):
            test_method = stripped[len("void "):].split("(")[0]
            break
    if test_method is None:
        raise SystemExit(f"CANNOT_RUN: found no test method in {test_source}")

    plans = repo / ".test-agent" / "plans" / target
    plans.mkdir(parents=True, exist_ok=True)

    (plans / "plan-v1.md").write_text(container("Test Plan: " + target, {
        "schema_version": 1,
        "plan_version": 1,
        "target": {"class": target},
        "mode": "legacy",
        "characterization": True,
        "status": "READY",
        "context": {"target_sha": sha, "notes": ["written by smoke_pipeline.py"]},
        "scenarios": [{
            "id": "TC01",
            "change": "NEW",
            "implementation": "PENDING",
            "description": "smoke scenario: the existing test class runs",
            "priority": "high",
            "evidence_strength": "strong",
            "evidence": [{"type": "existing_test",
                          "ref": f"{test_source.stem}#{test_method}"}],
        }],
        "deferred": [],
    }), encoding="utf-8")

    (plans / "generation-report-v1.md").write_text(container("Generation Report: " + target, {
        "schema_version": 1,
        "plan_version": 1,
        "target": {"class": target},
        "test_files": [test_source.relative_to(repo).as_posix()],
        "results": [{"id": "TC01", "status": "IMPLEMENTED", "test_method": test_method}],
    }), encoding="utf-8")

    return plans, test_source.stem


def run_script(name: str, repo: Path, target: str, extra: list) -> int:
    command = [sys.executable, str(REVIEWER / name), target, "--repo", str(repo),
               "--iteration", "1", *extra]
    print(f"\n$ {' '.join(command[1:])}", flush=True)
    result = subprocess.run(command, cwd=repo, capture_output=True, text=True)
    for line in (result.stdout + result.stderr).splitlines():
        print(f"  {line}")
    return result.returncode


def check_report(repo: Path, target: str, name: str, failures: list) -> None:
    path = repo / ".test-agent" / "checks" / target / name
    if not path.is_file():
        failures.append(f"{name} was not written")
        return
    try:
        data, _ = load_payload(path)
    except ValueError as exc:
        failures.append(f"{name} does not parse: {exc}")
        return
    if "status" not in data:
        failures.append(f"{name} has no status field")
        return
    print(f"  report {name}: status={data['status']}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", default="SimpleCalculatorService")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--skip-mutation", action="store_true",
                        help="skip PIT, which is the slowest of the three")
    parser.add_argument("--keep", action="store_true",
                        help="keep .test-agent afterwards (CI uploads the reports)")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    target = args.target
    plans, test_class = setup(repo, target)
    print(f"smoke target: {target} (tests: {test_class}), artifacts in {plans}")

    failures = []
    steps = [("run_tests.py", ["--repeat", "1"], "tests-r1.md"),
             ("coverage.py", [], "coverage-r1.md")]
    if not args.skip_mutation:
        steps.append(("mutation.py", [], "mutation-r1.md"))

    for script, extra, report in steps:
        code = run_script(script, repo, target, extra)
        # Exit 1 is a verdict about the tests; exit 2 is a broken pipeline.
        if code == 2:
            failures.append(f"{script} exited 2 — the check could not run")
        elif code not in (0, 1):
            failures.append(f"{script} exited {code}, which is not a defined code")
        else:
            print(f"  {script} exited {code} (ran)")
        check_report(repo, target, report, failures)

    if not args.keep:
        shutil.rmtree(repo / ".test-agent", ignore_errors=True)

    print()
    if failures:
        print(f"SMOKE_FAILED ({len(failures)}):")
        for failure in failures:
            print(f"  - {failure}")
        return 1
    print("PIPELINE_SMOKE_OK — every check script ran and wrote a readable report")
    return 0


if __name__ == "__main__":
    sys.exit(main())
